"""Add File and Tag models

Revision ID: 14f9c60a42f7
Revises: a3259da4e160
Create Date: 2024-10-02 11:33:45.029139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f9c60a42f7'
down_revision = 'a3259da4e160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('path', sa.String(length=255), nullable=False),
        sa.Column('size', sa.BigInteger(), nullable=False),
        sa.Column('type', sa.String(length=100), nullable=False),
        sa.Column('duration', sa.String(length=10), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
    )
    op.create_table('tags',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('file_tags',
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_tags')
    op.drop_table('tags')
    op.drop_table('files')
    # ### end Alembic commands ###
