"""Add File and Tag models with many-to-many relationship

Revision ID: 90d87ba9bd47
Revises: b984b5ed8d07
Create Date: 2024-10-02 15:11:08.813740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90d87ba9bd47'
down_revision = 'b984b5ed8d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_files_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_path'), ['path'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_files_size'))
        batch_op.drop_index(batch_op.f('ix_files_path'))
        batch_op.drop_index(batch_op.f('ix_files_filename'))
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
